// Kisan Saathi - 33 Screens Dataset for Interactive Prototype
window.KISAN_SCREENS = [
  {
    id: 1,
    category: "onboarding",
    title: "Splash / Welcome",
    titleHi: "स्वागत स्क्रीन",
    titlePa: "ਜੀ ਆਇਆਂ ਨੂੰ",
    tagline: "Your Crop Health Companion",
    taglineHi: "आपकी फसल का सच्चा साथी",
    image: "../generated_screens/screen_01.png",
    nextScreen: 2,
    prevScreen: null,
    description: "Establishes product identity, calm agricultural branding, and initial language selection.",
    descriptionHi: "उत्पाद पहचान, शांत कृषि सौंदर्य और प्रारंभिक भाषा चयन स्थापित करता है।",
    widgets: ["Brand Logo", "Tagline", "Language Selector", "Get Started CTA", "Guest Demo Link"],
    keyAction: "Get Started / शुरू करें"
  },
  {
    id: 2,
    category: "onboarding",
    title: "Language Selection",
    titleHi: "भाषा चयन",
    titlePa: "ਭਾਸ਼ਾ ਦੀ ਚੋਣ",
    tagline: "Choose Your Preferred Language",
    taglineHi: "अपनी पसंदीदा भाषा चुनें",
    image: "../generated_screens/screen_02.png",
    nextScreen: 3,
    prevScreen: 1,
    description: "Allows farmers to select Hindi, English, or Punjabi with voice preview support.",
    descriptionHi: "किसानों को आवाज पूर्वावलोकन के साथ हिन्दी, अंग्रेजी या पंजाबी चुनने की सुविधा।",
    widgets: ["Large Language Cards", "Voice Preview Buttons", "Audio Greeting", "Continue Button"],
    keyAction: "आगे बढ़ें / Continue"
  },
  {
    id: 3,
    category: "onboarding",
    title: "Login / Farmer Profile",
    titleHi: "किसान लॉगिन व प्रोफ़ाइल",
    titlePa: "ਕਿਸਾਨ ਲੌਗਇਨ",
    tagline: "Simple Mobile & OTP Verification",
    taglineHi: "सरल मोबाइल नंबर और ओटीपी सत्यापन",
    image: "../generated_screens/screen_03.png",
    nextScreen: 4,
    prevScreen: 2,
    description: "Lightweight, secure farmer authentication with phone number and 4-digit OTP.",
    descriptionHi: "फोन नंबर और 4-अंकीय ओटीपी के साथ हल्का, सुरक्षित किसान प्रमाणीकरण।",
    widgets: ["Mobile Number (+91)", "OTP Input", "Resend Timer", "Remember Me", "Verify CTA"],
    keyAction: "सत्यापित करें / Verify"
  },
  {
    id: 4,
    category: "onboarding",
    title: "Create Farm Profile",
    titleHi: "नया खेत जोड़ें",
    titlePa: "ਨਵਾਂ ਖੇਤ ਜੋੜੋ",
    tagline: "Establish Personal Farm Memory",
    taglineHi: "खेत का विवरण दर्ज करें",
    image: "../generated_screens/screen_04.png",
    nextScreen: 5,
    prevScreen: 3,
    description: "Captures farm name, GPS location, acreage, primary crop, and irrigation method.",
    descriptionHi: "खेत का नाम, जीपीएस स्थान, एकड़, मुख्य फसल और सिंचाई विधि दर्ज करता है।",
    widgets: ["Farm Name", "GPS Location Picker", "Area Stepper", "Crop Icons", "Irrigation Chips", "Save Farm"],
    keyAction: "खेत सुरक्षित करें / Save Farm"
  },
  {
    id: 5,
    category: "farmer_core",
    title: "Home / Farmer Dashboard",
    titleHi: "मुख्य डैशबोर्ड",
    titlePa: "ਮੁੱਖ ਡੈਸ਼ਬੋਰਡ",
    tagline: "Clear Health Score & Instant Actions",
    taglineHi: "फसल स्वास्थ्य स्कोर और त्वरित कार्रवाई",
    image: "../generated_screens/screen_05.png",
    nextScreen: 7,
    prevScreen: 4,
    description: "The primary hub: Farm Health Score (82/100), Scan Crop CTA, Voice Assistant, and Today's Advisory.",
    descriptionHi: "मुख्य स्क्रीन: फार्म स्वास्थ्य स्कोर (82/100), फसल स्कैन, आवाज सहायक और आज की मुख्य सलाह।",
    widgets: ["Farm Health Gauge (82/100)", "Scan Crop Card", "Speak Problem Card", "Today's Advisory Banner", "Weather Widget", "Bottom Navigation"],
    keyAction: "फसल स्कैन करें / Scan Crop"
  },
  {
    id: 6,
    category: "farmer_core",
    title: "My Farms & Crop Selection",
    titleHi: "मेरे खेत और फसलें",
    titlePa: "ਮੇਰੇ ਖੇਤ ਅਤੇ ਫਸਲਾਂ",
    tagline: "Manage Multiple Plots & Crops",
    taglineHi: "विभिन्न खेतों और फसलों का प्रबंधन",
    image: "../generated_screens/screen_06.png",
    nextScreen: 7,
    prevScreen: 5,
    description: "Overview of multiple plots (North Field Tomato, Canal Field Wheat, South Plot Cotton) with health badges.",
    descriptionHi: "कई खेतों का अवलोकन (उत्तर खेत टमाटर, नहर खेत गेहूं) स्वास्थ्य स्कोर और जोखिम स्तर के साथ।",
    widgets: ["Plot Cards", "Crop Health Chips", "Risk Badges", "Last Scan Timestamp", "+ Add Farm CTA"],
    keyAction: "फसल जांचें / Scan Plot"
  },
  {
    id: 7,
    category: "farmer_core",
    title: "Crop Scan / Multimodal Input",
    titleHi: "फसल जांच (मल्टीमोडल)",
    titlePa: "ਫਸਲ ਜਾਂਚ",
    tagline: "Multi-Angle Photos & Voice Input",
    taglineHi: "विभिन्न कोणों से फोटो और आवाज द्वारा लक्षण",
    image: "../generated_screens/screen_07.png",
    nextScreen: 8,
    prevScreen: 5,
    description: "Collects leaf front, leaf back, stem, and whole plant photos with optional voice description.",
    descriptionHi: "पत्ते के आगे-पीछे, तने और पूरे पौधे की फोटो के साथ बोलकर लक्षण बताने की सुविधा।",
    widgets: ["4-Slot Photo Grid", "Viewfinder Silhouette Guides", "Voice Description Mic", "Symptom Quick Tags", "Analyze CTA"],
    keyAction: "विश्लेषण करें / Analyze Crop"
  },
  {
    id: 8,
    category: "farmer_core",
    title: "Image Quality Check",
    titleHi: "फोटो गुणवत्ता जांच",
    titlePa: "ਫੋਟੋ ਕੁਆਲਿਟੀ ਜਾਂਚ",
    tagline: "Real-time Blur & Lighting Feedback",
    taglineHi: "धुंधलापन और रोशनी की तत्काल जांच",
    image: "../generated_screens/screen_08.png",
    nextScreen: 10,
    prevScreen: 7,
    description: "Prevents poor decisions by verifying clarity, lighting, and framing before inference.",
    descriptionHi: "स्पष्टता, रोशनी और फोकस की पुष्टि करके गलत सलाह से बचाव करता है।",
    widgets: ["Photo Inspection Box", "Quality Status Badge", "Good vs Bad Photo Tips", "Retake Button", "Proceed CTA"],
    keyAction: "आगे बढ़ें / Proceed"
  },
  {
    id: 9,
    category: "farmer_core",
    title: "Voice Assistant",
    titleHi: "आवाज सहायक",
    titlePa: "ਆਵਾਜ਼ ਸਹਾਇਕ",
    tagline: "Speak Symptoms in Local Language",
    taglineHi: "अपनी भाषा में बोलकर समस्या बताएं",
    image: "../generated_screens/screen_09.png",
    nextScreen: 10,
    prevScreen: 7,
    description: "Large pulsating microphone with speech-to-text transcript confirmation in Hindi.",
    descriptionHi: "बड़ा स्पंदनशील माइक बटन, हिन्दी में बात पहचान और पुष्टि कार्ड।",
    widgets: ["Pulsing Mic Button", "Soundwave Animation", "Speech Transcript Card", "Confirmation Pills", "Speak Again"],
    keyAction: "हाँ, आगे बढ़ें / Yes, Proceed"
  },
  {
    id: 10,
    category: "farmer_core",
    title: "Clarifying Questions",
    titleHi: "स्पष्टीकरण प्रश्न",
    titlePa: "ਸਪਸ਼ਟੀਕਰਨ ਸਵਾਲ",
    tagline: "Fill Evidence Gaps Accurately",
    taglineHi: "सटीक परिणाम के लिए संक्षिप्त प्रश्न",
    image: "../generated_screens/screen_10.png",
    nextScreen: 11,
    prevScreen: 8,
    description: "Asks 1-2 simple questions (e.g., spots on underside of leaves?) when confidence needs refinement.",
    descriptionHi: "कम निश्चितता होने पर 1-2 सरल प्रश्न (जैसे पत्तों के नीचे धब्बे हैं?) पूछता है।",
    widgets: ["Step Progress (1/2)", "Illustrated Question Card", "Large Yes / No / Not Sure Buttons", "Audio Readout", "Skip Link"],
    keyAction: "उत्तर दें / Submit Answer"
  },
  {
    id: 11,
    category: "diagnosis",
    title: "Analysis Progress",
    titleHi: "विश्लेषण प्रगति",
    titlePa: "ਵਿਸ਼ਲੇਸ਼ਣ ਪ੍ਰਗਤੀ",
    tagline: "Transparent, Jargon-Free Processing",
    taglineHi: "स्पष्ट और पारदर्शी प्रगति चरण",
    image: "../generated_screens/screen_11.png",
    nextScreen: 12,
    prevScreen: 10,
    description: "Displays 5 calm, friendly stages (checking photos, symptoms, conditions, patterns, advice).",
    descriptionHi: "5 शांत और सरल चरणों में प्रक्रिया दिखाता है (फोटो जांच, लक्षण मिलान, मौसम जांच, सलाह तैयारी)।",
    widgets: ["Magnifying Glass Illustration", "5-Stage Checklist", "Pulsing Status Dots", "Friendly Reassurance Message"],
    keyAction: "परिणाम देखें / View Result"
  },
  {
    id: 12,
    category: "diagnosis",
    title: "Diagnosis Result",
    titleHi: "निदान परिणाम",
    titlePa: "ਨਿਦਾਨ ਨਤੀਜਾ",
    tagline: "Condition, Confidence & Severity",
    taglineHi: "बीमारी का नाम, निश्चितता और गंभीरता",
    image: "../generated_screens/screen_12.png",
    nextScreen: 15,
    prevScreen: 11,
    description: "Main finding: Tomato Early Blight, 91% Confidence, High Risk, with immediate action buttons.",
    descriptionHi: "मुख्य खोज: टमाटर अगेती झुलसा, 91% निश्चितता, उच्च जोखिम और आवश्यक कदम।",
    widgets: ["Disease Name & Image", "Confidence Meter (91%)", "Severity Badge (High)", "Why this result?", "What Should I Do Today?"],
    keyAction: "आज क्या करें? / What Should I Do Today?"
  },
  {
    id: 13,
    category: "diagnosis",
    title: "Explainable AI & Heatmap",
    titleHi: "परिणाम का कारण (एक्सप्लेनेबल एआई)",
    titlePa: "ਨਤੀਜੇ ਦਾ ਕਾਰਨ",
    tagline: "Visual Highlights & Risk Drivers",
    taglineHi: "पत्ते पर प्रभावित हिस्से और जोखिम के कारक",
    image: "../generated_screens/screen_13.png",
    nextScreen: 14,
    prevScreen: 12,
    description: "Highlights key leaf lesion areas with plain-language explanation of weather and symptom drivers.",
    descriptionHi: "पत्ते के प्रभावित हिस्से को उजागर करता है और मौसम व लक्षणों के प्रभाव को सरल भाषा में समझाता है।",
    widgets: ["Highlighted Leaf Heatmap", "Observed Signs Card", "Risk Factors (Humidity 82%, 26°C)", "Audio Explanation CTA"],
    keyAction: "जोखिम डैशबोर्ड / View Risk"
  },
  {
    id: 14,
    category: "diagnosis",
    title: "Crop Health & Risk Dashboard",
    titleHi: "फसल स्वास्थ्य व समग्र जोखिम",
    titlePa: "ਫਸਲ ਜੋਖਮ ਡੈਸ਼ਬੋਰਡ",
    tagline: "Multi-Signal Evidence Synthesis",
    taglineHi: "तस्वीर, मौसम, इतिहास और स्थान का संयुक्त विश्लेषण",
    image: "../generated_screens/screen_14.png",
    nextScreen: 15,
    prevScreen: 13,
    description: "Combines image evidence, weather risk, farm history, crop stage, and nearby disease activity into an overall risk score.",
    descriptionHi: "फोटो, मौसम, खेत का इतिहास और नजदीकी रोग गतिविधि को मिलाकर समग्र जोखिम निर्धारित करता है।",
    widgets: ["Composite Risk Gauge (HIGH)", "5 Factor Signal Bars", "Plain-Language Synthesis Card", "Action CTA"],
    keyAction: "कार्ययोजना देखें / Action Plan"
  },
  {
    id: 15,
    category: "advisory",
    title: "\"What Should I Do Today?\"",
    titleHi: "आज क्या करें? (दैनिक कार्ययोजना)",
    titlePa: "ਅੱਜ ਕੀ ਕਰਨਾ ਹੈ?",
    tagline: "Prioritized, Actionable Care Steps",
    taglineHi: "प्राथमिकता के अनुसार आज के जरूरी कदम",
    image: "../generated_screens/screen_15.png",
    nextScreen: 16,
    prevScreen: 12,
    description: "Core actionable advisory divided into DO NOW, MONITOR, ROUTINE, and NEXT SCAN with voice playback.",
    descriptionHi: "अति आवश्यक कदम: DO NOW (तुरंत करें), MONITOR (निगरानी), ROUTINE (नियमित देखभाल), NEXT SCAN (अगली जांच)।",
    widgets: ["Listen Audio CTA", "DO NOW Urgent Card", "MONITOR Card", "ROUTINE Card", "NEXT SCAN Card", "Mark as Done CTA"],
    keyAction: "कदम पूरा किया / Mark Done"
  },
  {
    id: 16,
    category: "advisory",
    title: "Advisory Details & Precautions",
    titleHi: "विस्तृत कृषि सलाह व सावधानियां",
    titlePa: "ਵਿਸਤ੍ਰਿਤ ਸਲਾਹ",
    tagline: "Dos, Don'ts & Trusted Sources",
    taglineHi: "उपचार, क्या न करें और प्रमाणित स्रोत",
    image: "../generated_screens/screen_16.png",
    nextScreen: 18,
    prevScreen: 15,
    description: "Detailed tabs for organic spray dosage, practices to avoid (what NOT to do), and ICAR verified references.",
    descriptionHi: "जैविक उपचार (नीम तेल), दोपहर में स्प्रे न करने की चेतावनी और आईसीएआर प्रमाणित स्रोत।",
    widgets: ["Treatment / Precautions / Organic Tabs", "Dosage Card", "What to Avoid Warnings", "ICAR Trust Badge", "KVK Helpline CTA"],
    keyAction: "फॉलो-अप रिमाइंडर / Set Reminder"
  },
  {
    id: 17,
    category: "advisory",
    title: "Offline Mode & Pending Sync",
    titleHi: "ऑफ़लाइन मोड व डेटा सिंक",
    titlePa: "ਔਫਲਾਈਨ ਮੋਡ",
    tagline: "Work Seamlessly Without Connectivity",
    taglineHi: "बिना इंटरनेट के फोटो लें और सलाह देखें",
    image: "../generated_screens/screen_17.png",
    nextScreen: 5,
    prevScreen: 15,
    description: "Shows offline status, cached advisories, farm diary, and a queue of 3 items waiting to sync upon reconnection.",
    descriptionHi: "ऑफ़लाइन संकेत, कैश्ड सलाह, खेत डायरी और इंटरनेट आने पर 3 वस्तुओं का स्वतः सिंक होना दिखाता है।",
    widgets: ["Amber Offline Banner", "Pending Queue Card (3 items)", "Offline Tools Grid", "Auto-Sync Notification"],
    keyAction: "सिंक करें / Sync When Online"
  },
  {
    id: 18,
    category: "followup",
    title: "Follow-Up Reminder",
    titleHi: "फॉलो-अप अनुस्मारक",
    titlePa: "ਫਾਲੋ-ਅੱਪ ਰੀਮਾਈਂਡਰ",
    tagline: "5-Day Checkup for Disease Recovery",
    taglineHi: "उपचार के 5 दिन बाद पुनः जांच की याद",
    image: "../generated_screens/screen_18.png",
    nextScreen: 19,
    prevScreen: 16,
    description: "Proactive alert prompting farmer to take a follow-up scan to verify whether crop condition is improving.",
    descriptionHi: "उपचार के बाद फसल में सुधार की पुष्टि के लिए 5वें दिन नई फोटो लेने का अनुस्मारक।",
    widgets: ["Calendar Reminder Icon", "Previous Severity (40%) Card", "Take Follow-Up Scan CTA", "Remind Tomorrow Link"],
    keyAction: "नई फोटो लें / Take Follow-Up"
  },
  {
    id: 19,
    category: "followup",
    title: "Follow-Up Scan Comparison",
    titleHi: "तुलनात्मक फोटो जांच",
    titlePa: "ਤੁਲਨਾਤਮਕ ਸਕੈਨ",
    tagline: "Side-by-Side Day 1 vs Day 5 View",
    taglineHi: "पहले दिन और 5वें दिन की फोटो का आमने-सामने मिलान",
    image: "../generated_screens/screen_19.png",
    nextScreen: 20,
    prevScreen: 18,
    description: "Side-by-side viewfinder comparing initial baseline scan with live camera viewfinder from the same angle.",
    descriptionHi: "पुराने स्कैन और आज के लाइव कैमरे की आमने-सामने तुलना, समान कोण के लिए ओवरले गाइड।",
    widgets: ["Day 1 Photo Frame", "Live Camera Viewfinder", "Leaf Alignment Ghost Guide", "Same Plot Confirmation", "Compare CTA"],
    keyAction: "तुलना करें / Compare Scans"
  },
  {
    id: 20,
    category: "followup",
    title: "Disease Progression Timeline",
    titleHi: "रोग प्रगति समयरेखा",
    titlePa: "ਬਿਮਾਰੀ ਦੀ ਪ੍ਰਗਤੀ",
    tagline: "Improved, Stable or Worsening Trend",
    taglineHi: "सुधार, स्थिरता या रोग वृद्धि का ग्राफ",
    image: "../generated_screens/screen_20.png",
    nextScreen: 21,
    prevScreen: 19,
    description: "Visual timeline tracking severity drop: Day 1 (40%) -> Day 5 (22%) -> Day 10 (10%) with recovery trend.",
    descriptionHi: "गंभीरता में कमी की समयरेखा: दिन 1 (40%) -> दिन 5 (22%) -> दिन 10 (10%) के साथ सुधार का स्पष्ट संकेत।",
    widgets: ["Condition: IMPROVED Badge", "3-Node Recovery Timeline", "Severity Trend Curve", "Recovery Explanation", "View Updated Advice CTA"],
    keyAction: "उपचार असर देखें / Treatment Effect"
  },
  {
    id: 21,
    category: "followup",
    title: "Treatment Response Tracking",
    titleHi: "उपचार प्रतिक्रिया विश्लेषण",
    titlePa: "ਇਲਾਜ ਪ੍ਰਤੀਕਰਿਆ",
    tagline: "Correlate Interventions with Changes",
    taglineHi: "दवा छिड़काव के बाद सुधार का आकलन",
    image: "../generated_screens/screen_21.png",
    nextScreen: 22,
    prevScreen: 20,
    description: "Evaluates impact of reported intervention (Neem Oil spray on Day 2) with careful non-causal wording.",
    descriptionHi: "किसान द्वारा किए गए नीम तेल स्प्रे के बाद सुधार का विश्लेषण, वैज्ञानिक रूप से संतुलित शब्दों में।",
    widgets: ["Before vs After Severity (40% -> 20%)", "Reported Intervention Log", "Positive Response Observed Badge", "Save to Diary CTA"],
    keyAction: "अनुकूली सलाह / Adaptive Action"
  },
  {
    id: 22,
    category: "followup",
    title: "Adaptive Follow-Up Action",
    titleHi: "अनुकूली सलाह व अगली योजना",
    titlePa: "ਅਨੁਕੂਲ ਕਾਰਵਾਈ",
    tagline: "Dynamic Guidance Based on Recovery",
    taglineHi: "सुधार के आधार पर स्वतः बदली हुई सलाह",
    image: "../generated_screens/screen_22.png",
    nextScreen: 23,
    prevScreen: 21,
    description: "Adapts recommendations: stops spray, switches to light monitoring, and reschedules next scan for 7 days.",
    descriptionHi: "सुधार होने पर स्प्रे रोकने की सलाह, नियमित निगरानी और 7 दिन बाद अंतिम पुष्टि की योजना।",
    widgets: ["Dynamic Action Updated Banner", "Stop Spray Card", "Light Monitoring Card", "7-Day Rescan Card", "Accept CTA"],
    keyAction: "स्वीकार करें / Accept & Set Reminder"
  },
  {
    id: 23,
    category: "expert",
    title: "Expert Help Request",
    titleHi: "विशेषज्ञ सहायता अनुरोध",
    titlePa: "ਮਾਹਰ ਦੀ ਮਦਦ",
    tagline: "Escalate Ambiguous or Severe Cases",
    taglineHi: "कठिन या गंभीर मामलों में विशेषज्ञ से परामर्श",
    image: "../generated_screens/screen_23.png",
    nextScreen: 24,
    prevScreen: 12,
    description: "Enables farmers to escalate low-confidence or worsening cases to extension workers with voice notes.",
    descriptionHi: "कम निश्चितता या बिगड़ते मामलों में आवाज संदेश के साथ कृषि वैज्ञानिक से सलाह लेने का फॉर्म।",
    widgets: ["Case Summary Card", "Voice Note Recorder", "Channel Selector (WhatsApp/Call/App)", "Status Tracker (Under Review)", "Submit CTA"],
    keyAction: "विशेषज्ञ को भेजें / Submit to Expert"
  },
  {
    id: 24,
    category: "expert",
    title: "Expert / Extension Case Queue",
    titleHi: "विस्तार कार्यकर्ता केस डैशबोर्ड",
    titlePa: "ਮਾਹਰ ਕੇਸ ਸੂਚੀ",
    tagline: "Triage & Prioritize Farmer Cases",
    taglineHi: "गंभीरता और जोखिम के आधार पर मामलों का वर्गीकरण",
    image: "../generated_screens/screen_24.png",
    nextScreen: 25,
    prevScreen: 23,
    description: "Priority queue for extension workers categorized by urgent, low-confidence, and unresolved field cases.",
    descriptionHi: "विस्तार कार्यकर्ताओं के लिए प्राथमिकताप्राप्त केस कतार (उच्च जोखिम, कम निश्चितता, लंबित केस)।",
    widgets: ["Filter Tabs (All/Urgent/Review/Resolved)", "Patient Case Cards", "Farmer Name & Plot", "Priority Badge", "Open Case CTA"],
    keyAction: "केस खोलें / Open Case"
  },
  {
    id: 25,
    category: "expert",
    title: "Expert Case Detail & Validation",
    titleHi: "केस सत्यापन व विशेषज्ञ परामर्श",
    titlePa: "ਕੇਸ ਵੇਰਵਾ ਅਤੇ ਪੁਸ਼ਟੀ",
    tagline: "High-Res Images, Context & Override",
    taglineHi: "उच्च गुणवत्ता फोटो, मौसम डेटा और निदान संशोधन",
    image: "../generated_screens/screen_25.png",
    nextScreen: 26,
    prevScreen: 24,
    description: "Detailed diagnostic cockpit: multi-photo gallery, weather context, confirm/override AI, and custom advisory dispatch.",
    descriptionHi: "वैज्ञानिक जांच स्क्रीन: फोटो गैलरी, मौसम संदर्भ, एआई निदान की पुष्टि या संशोधन, और किसान को परामर्श प्रेषण।",
    widgets: ["High-Res Photo Viewer", "AI Suggestion Card", "Context Drawer (Soil, Weather)", "Confirm / Override Radios", "Refer to Lab CTA", "Dispatch Advisory CTA"],
    keyAction: "सलाह भेजें / Dispatch Advisory"
  },
  {
    id: 26,
    category: "expert",
    title: "Laboratory Referral",
    titleHi: "प्रयोगशाला रेफरल व जांच",
    titlePa: "ਲੈਬ ਰੈਫਰਲ",
    tagline: "Sample Tracking for Complex Diseases",
    taglineHi: "जटिल रोगों के लिए लैब नमूना ट्रैकिंग",
    image: "../generated_screens/screen_26.png",
    nextScreen: 27,
    prevScreen: 25,
    description: "Generates QR-coded lab referral for fungal culture/PCR with sample lifecycle tracking.",
    descriptionHi: "क्यूआर कोड के साथ लैब रेफरल रसीद, नमूना संग्रह निर्देश और परीक्षण की लाइव स्थिति।",
    widgets: ["Sample ID & QR Code", "Suspected Pathogen Card", "Sampling Instructions", "Lifecycle Timeline (Sent -> Testing -> Result)", "Download Report CTA"],
    keyAction: "रिपोर्ट डाउनलोड करें / Download Report"
  },
  {
    id: 27,
    category: "monitoring",
    title: "Notifications & Outbreak Alerts",
    titleHi: "सूचनाएं व क्षेत्रीय अलर्ट",
    titlePa: "ਸੂਚਨਾਵਾਂ ਅਤੇ ਚੇਤਾਵਨੀਆਂ",
    tagline: "Urgent Regional Outbreak Warnings",
    taglineHi: "क्षेत्रीय बीमारी का प्रकोप और समय पर चेतावनी",
    image: "../generated_screens/screen_27.png",
    nextScreen: 28,
    prevScreen: 5,
    description: "Alert center categorizing urgent district outbreak warnings, follow-up reminders, and expert responses.",
    descriptionHi: "जिले में झुलसा रोग के प्रकोप की त्वरित चेतावनी, फॉलो-अप अनुस्मारक और विशेषज्ञ जवाब।",
    widgets: ["Notification Categories (Urgent/Important/Routine)", "Urgent Outbreak Card", "Follow-up Due Card", "Expert Advisory Arrived Card"],
    keyAction: "अलर्ट विवरण / View Alert"
  },
  {
    id: 28,
    category: "monitoring",
    title: "Farm Timeline & Personal Memory",
    titleHi: "खेत की याददाश्त (समयरेखा)",
    titlePa: "ਖੇਤ ਦੀ ਸਮਾਂ-ਰੇਖਾ",
    tagline: "Continuous Field History & Evolution",
    taglineHi: "खेत के इतिहास, जांच और उपचार की कालानुक्रमिक डायरी",
    image: "../generated_screens/screen_28.png",
    nextScreen: 29,
    prevScreen: 27,
    description: "Chronological feed of all scans, diagnosis results, spray interventions, and weather impacts over the season.",
    descriptionHi: "पूरे सीजन के स्कैन, रोग पहचान, किए गए उपचार और मौसम के प्रभाव की संपूर्ण डायरी।",
    widgets: ["Interactive Vertical Timeline", "Plot Filter Chips", "Event Cards with Photos", "Memory Reassurance Message"],
    keyAction: "फार्म स्कोर देखें / View Farm Score"
  },
  {
    id: 29,
    category: "monitoring",
    title: "Farm Health Score Deep Dive",
    titleHi: "फार्म हेल्थ स्कोर विस्तृत विश्लेषण",
    titlePa: "ਫਾਰਮ ਹੈਲਥ ਸਕੋਰ",
    tagline: "82/100 Multi-Factor Evaluation",
    taglineHi: "82/100 स्वास्थ्य स्कोर के घटकों का विश्लेषण",
    image: "../generated_screens/screen_29.png",
    nextScreen: 30,
    prevScreen: 28,
    description: "Comprehensive breakdown of the 82/100 score across disease index, weather resilience, and treatment response.",
    descriptionHi: "82/100 स्कोर का विवरण: रोग प्रतिरोधक क्षमता (85), मौसम अनुकूलता (68), उपचार अनुपालन (95)।",
    widgets: ["Circular Speedometer (82/100)", "+8 Pt Trend Arrow", "4 Pillar Progress Bars", "Improvement Advice Card"],
    keyAction: "क्षेत्रीय नक्शा देखें / View Regional Map"
  },
  {
    id: 30,
    category: "monitoring",
    title: "Nearby Risk & GIS Map View",
    titleHi: "आस-पास का जोखिम व जीआईएस नक्शा",
    titlePa: "ਨੇੜਲਾ ਜੋਖਮ ਨਕਸ਼ਾ",
    tagline: "Community Hotspots Within 5km Radius",
    taglineHi: "5 किमी के दायरे में सामुदायिक रोग हॉटस्पॉट",
    image: "../generated_screens/screen_30.png",
    nextScreen: 31,
    prevScreen: 29,
    description: "Interactive GIS map showing anonymized disease clusters and outbreak density surrounding the farmer's village.",
    descriptionHi: "किसान के खेत के 5 किमी दायरे में अज्ञात सामुदायिक रोग समूहों और हॉटस्पॉट का स्पष्ट नक्शा।",
    widgets: ["Topographic Map View", "My Farm Pin", "Anonymized Disease Heat Circles", "Nearby Cases Banner (12 reported)", "Preventive Advice CTA"],
    keyAction: "मौसम जोखिम देखें / Weather Risk"
  },
  {
    id: 31,
    category: "monitoring",
    title: "Weather & Crop Risk Forecast",
    titleHi: "मौसम और फसल जोखिम पूर्वानुमान",
    titlePa: "ਮੌਸਮ ਅਤੇ ਜੋਖਮ",
    tagline: "Humidity, Rainfall & Fungal Correlation",
    taglineHi: "आर्द्रता, बारिश और फफूंद रोग का संबंध",
    image: "../generated_screens/screen_31.png",
    nextScreen: 32,
    prevScreen: 30,
    description: "7-day forecast correlating high humidity (>80%) and temperature with heightened fungal blight vulnerability.",
    descriptionHi: "7-दिवसीय मौसम पूर्वानुमान जो उच्च आर्द्रता (>80%) के कारण झुलसा रोग के बढ़ते खतरे की चेतावनी देता है।",
    widgets: ["Current Weather Card (27°C, 84% humidity)", "5-Day Forecast Strip", "Fungal Risk Correlation Banner", "Farmer Spray Tip"],
    keyAction: "फीडबैक दें / Give Feedback"
  },
  {
    id: 32,
    category: "settings",
    title: "Farmer Feedback & Outcome Report",
    titleHi: "किसान फीडबैक व परिणाम",
    titlePa: "ਕਿਸਾਨ ਫੀਡਬੈਕ",
    tagline: "Verify Ground Truth & Advice Impact",
    taglineHi: "सलाह के असर और सुधार की जानकारी दें",
    image: "../generated_screens/screen_32.png",
    nextScreen: 33,
    prevScreen: 31,
    description: "Collects field ground truth: Did crop improve? Voice feedback recording and follow-up outcome photo upload.",
    descriptionHi: "सलाह की उपयोगिता, सुधार का स्तर (4 स्माइली विकल्प), बोलकर फीडबैक और परिणाम फोटो अपलोड।",
    widgets: ["4 Improvement Status Smileys", "Voice Feedback Recorder", "After-Treatment Photo Slot", "5-Star Rating", "Submit CTA"],
    keyAction: "फीडबैक सबमिट करें / Submit Feedback"
  },
  {
    id: 33,
    category: "settings",
    title: "Settings & Preferences",
    titleHi: "सेटिंग्स व प्राथमिकताएं",
    titlePa: "ਸੈਟਿੰਗਾਂ",
    tagline: "Language, Audio Speed & Offline Storage",
    taglineHi: "भाषा, आवाज गति और ऑफ़लाइन स्टोरेज नियंत्रण",
    image: "../generated_screens/screen_33.png",
    nextScreen: 5,
    prevScreen: 32,
    description: "Farmer profile, language switcher, voice speed, offline cache manager (32MB), notification preferences, and Krishi helpline.",
    descriptionHi: "प्रोफ़ाइल, भाषा परिवर्तन, आवाज गति, ऑफ़लाइन स्टोरेज प्रबंधन (32MB), अधिसूचनाएं और कृषि हेल्पलाइन।",
    widgets: ["Profile Card (Ramesh Kumar)", "Language Switcher (हिन्दी)", "Voice Speed Slider", "Offline Cache Manager", "Manage Farms", "Krishi Helpline", "Logout"],
    keyAction: "होम पर लौटें / Back to Home"
  }
];
